externalization

diff --git a/run_sim b/run_sim
--- a/run_sim
+++ b/run_sim
@@ -2,23 +2,60 @@
 
 show_help() {
   cat <<EOF
-usage: run_sim <start|stop|restart|console> <user_name> <sim name>
+usage: run_sim <start|stop|restart|console> <sim name> [user_name]
 EOF
   exit 1
 }
 
 # check if params
-if [ $# -lt 3 ];then
+if [ $# -lt 2 ];then
   show_help
   exit;
 fi
 
-# check if good user
-if [ ! "$(id -nu)" = "${2}" ]; then
-  #su - opensim -c "$0 $*"
-  sudo -i -u ${2} -- /usr/local/bin/run_sim $*
-  exit
+# fill params
+command=$1
+sim_name=$2
+user_name=$3
+
+# check the command
+case $command in
+  start)
+    ;;
+  stop)
+    ;;
+  restart)
+    ;;
+  console)
+    ;;
+  *)
+    show_help
+    exit 1;
+    ;;
+esac
+
+
+
+
+# ======================
+#      user test
+# ======================
+
+if [ $# -eq 3 ];then
+  # check if same user
+  if [ ! "$(id -nu)" = "${3}" ]; then
+    # check if user exists
+    if [ ! $(id -u "${3}" 2>/dev/null) ]; then
+      # re run using the other user rights
+      #su - opensim -c "$0 $*"
+      sudo -i -u ${3} -- /usr/local/bin/run_sim $*
+      exit
+    fi
+  fi
+else
+  user_name="$(id -nu)"
 fi
+
 
 # ======================
 #         config
@@ -28,10 +65,6 @@ if [ ! -f "/etc/ostmu/ostmu.conf" ]; then
   echo $"/etc/ostmu/ostmu.conf file not found."
   exit 1;
 fi
-
-command=$1
-user_name=$2
-sim_name=$3
 
 # include the config
 source "/etc/ostmu/ostmu.conf"
@@ -52,6 +85,9 @@ source "${OSTMU_FOLDER}/includes/users"
 source "${OSTMU_FOLDER}/includes/tmux"
 source "${OSTMU_FOLDER}/includes/sims"
 
+# ======================
+#      main program
+# ======================
 service_is_running() {
   check_sim ${user_name} ${sim_name}
   return $?;
@@ -68,12 +104,12 @@ do_start() {
     if [ ! $? -eq 0 ]; then
       tmux_create_session "${user_name}" "${sim_name}"
       run_simulator "${user_name}" "${sim_name}"
-      exit 0;
-    fi
-    check_sim ${user_name} ${sim_name}
-    # check if simulator is responding
-    if [ ! $? -eq 0 ]; then
-      run_simulator "${user_name}" "${sim_name}"
+    else
+      # check if simulator is responding
+      check_sim ${user_name} ${sim_name}
+      if [ ! $? -eq 0 ]; then
+        run_simulator "${user_name}" "${sim_name}"
+      fi
     fi
     exit 0;
   fi
@@ -81,28 +117,28 @@ do_start() {
 
 do_stop() {
   service_is_running
-  if [ ! $? -eq 0 ]; then
+  if [ $? -eq 0 ]; then
     stop_simulator ${user_name} ${sim_name}
   else
-    echo "The simulator ${sim_name} doesn't exist."
+    echo "Error stopping the simulator ${sim_name}."
     exit 1
   fi
 }
 
-case "$1" in
+case "$command" in
   start)
-    do_start $3
+    do_start ${sim_name}
     ;;
   stop)
-    do_stop $3
+    do_stop ${sim_name}
     ;;
   restart)
-    do_stop $3
-    sleep 5
-    do_start $3
+    do_stop ${sim_name}
+    sleep 10
+    do_start ${sim_name}
     ;;
   console)
-    ostmu ${sim_name}
+    tmux_attach_session ${user_name} ${sim_name}
     ;;
   *)
     show_help
